version: "3.3"
services:
  database:
    image: postgres
    #restart: always
    env_file:
      - ./config/env/.env
    ports:
      - 5432:5432
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: newsletter_server
    depends_on:
      - database
    command: scripts/start.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - config/env/.env
